// Generates src/puzzles.js: "find the best move" positions with a provable answer.
//   node test/make-puzzles.mjs [perTier=8] [workers=8] [maxGamesPerWorker=150] [minutes=40]
// The file is rewritten after every accepted puzzle, so stopping it early keeps what was found;
// it finishes when every tier is full, the games run out, or the time budget is spent.
// Tiers do not fill evenly: Medium and Hard (Advanced right where Intermediate is wrong, or only
// the Expert right) are much rarer than Easy and Master.
//
// Positions come from seeded Advanced-vs-Advanced self-play (each worker thread its own seed).
// A position becomes a puzzle only when Mr. Makis's analysis (two-ply ranking, then play-outs with
// the same dice for every candidate) finds a clear answer. Moves within SAME of the best are equally
// good and ALL count as correct (often the same checkers in another order); the best move outside
// that group must be >= GAP_CONFIRM worse in win chance. Screened with 60 play-outs, then CONFIRMED
// with 400 on independent dice; both runs must agree.
// Difficulty is measured, not guessed: which computer level already finds a correct move?
//   1 Easy   - the hand-set greedy evaluation (Intermediate without its noise)
//   2 Medium - only the tuned greedy evaluation (Advanced)
//   3 Hard   - only the Expert's two-ply search
//   4 Master - none of them; only the play-outs show it
// Theme = what separates the best move from the best wrong one (runner, wall, block, race, ...).
import { writeFileSync } from 'node:fs';
import { Worker, isMainThread, parentPort, workerData } from 'node:worker_threads';
import { newGame, viewOf, applySteps, winner, chooseMove, finalPositions, expandDice, analyzeView } from '../src/engine.js';

const GAP_SCREEN = 0.07, GAP_CONFIRM = 0.10, SAME = 0.03, MIN_LEGAL = 4;

if (isMainThread) {
  const PER_TIER = +process.argv[2] || 8, WORKERS = +process.argv[3] || 8, MAX_GAMES = +process.argv[4] || 150;
  const MINUTES = +process.argv[5] || 40;
  const tiers = { 1: [], 2: [], 3: [], 4: [] }, seen = new Set();
  const stats = { games: 0, tried: 0, screened: 0 };
  const t0 = Date.now();
  const full = () => Object.values(tiers).every((t) => t.length >= PER_TIER);
  const pool = [];
  let running = WORKERS;
  const write = () => {
    // order: by tier, then by gap (clearest first); ids follow that order
    const all = [1, 2, 3, 4].flatMap((t) => tiers[t].sort((x, y) => (y.win[0] - y.win[1]) - (x.win[0] - x.win[1])));
    const header = `// GENERATED by test/make-puzzles.mjs on ${new Date().toISOString().slice(0, 10)} - do not edit by hand; rerun it.
// ${all.length} puzzles from ${stats.games} self-play games (${stats.tried} positions analysed, ${stats.screened} passed the 60-play-out screen).
// Each: the side to move's view (mine/opp in its own numbering, 24 = start), the dice, Mr. Makis's best
// play, \`keys\` = every final position within ${SAME * 100} points of it (all accepted as correct), the best move
// outside that group ("second", >= ${GAP_CONFIRM * 100} points of win chance worse, confirmed with 400 play-outs),
// both win rates, the measured difficulty tier (1 Easy .. 4 Master) and a theme.
`;
    const lines = all.map((q, i) => '  ' + JSON.stringify({ id: i + 1, ...q }) + ',\n').join('');
    writeFileSync(new URL('../src/puzzles.js', import.meta.url), `${header}export const PUZZLES = [\n${lines}];\n`);
    return all.length;
  };
  const finish = () => {
    for (const w of pool) w.terminate();
    const n = write();
    console.log(`wrote ${n} puzzles (${[1, 2, 3, 4].map((t) => tiers[t].length).join('/')} per tier) in ${((Date.now() - t0) / 60000).toFixed(1)} min`);
    process.exit(0);
  };
  setTimeout(finish, MINUTES * 60000);
  for (let k = 0; k < WORKERS; k++) {
    const w = new Worker(new URL(import.meta.url), { workerData: { seed: 20261002 + k * 7919, maxGames: MAX_GAMES } });
    pool.push(w);
    w.on('message', (m) => {
      if (m.type === 'game') { stats.games++; stats.tried += m.tried; stats.screened += m.screened; return; }
      const q = m.puzzle, pk = q.posKey;
      if (seen.has(pk) || tiers[q.tier].length >= PER_TIER) return;
      seen.add(pk); delete q.posKey;
      tiers[q.tier].push(q);
      write();
      console.log(`tier ${q.tier} ${q.theme} gap ${((q.win[0] - q.win[1]) * 100).toFixed(0)} | have ${[1, 2, 3, 4].map((t) => tiers[t].length).join('/')} | ${stats.games} games | ${((Date.now() - t0) / 60000).toFixed(1)} min`);
      if (full()) finish();
    });
    w.on('exit', () => { if (--running === 0) finish(); });
  }
} else {
  let seed = workerData.seed;
  const rnd = () => { seed = (seed * 1103515245 + 12345) >>> 0; return seed / 4294967296; };
  const keyOf = (mine, off) => Array.from(mine).join(',') + '|' + off;
  const finalOf = (v, steps) => {
    const mine = Int8Array.from(v.mine); let off = v.myOff;
    for (const s of steps) { mine[s.r]--; if (s.t) mine[s.t]++; else off++; }
    return keyOf(mine, off);
  };
  const nearBlocks = (c) => c.newPts.filter((p) => p.near > 0).length;
  const theme = (best, second) => {
    const B = best.facts, A = second.facts;
    if (B.passed && !A.passed) return 'Runner';
    if (B.wall.len > A.wall.len) return 'Wall';
    if (nearBlocks(best) > nearBlocks(second)) return 'Block';
    if (B.off > A.off) return 'Bear-off';
    if (!B.contact) return 'Race';
    if (B.meHemmed < A.meHemmed - 1) return 'Mobility';
    if (B.stack < A.stack) return 'Spread';
    return 'Judgement';
  };
  const split = (cands) => {
    const top = cands[0];
    return { top, ok: cands.filter((c) => c.win >= top.win - SAME), next: cands.find((c) => c.win < top.win - SAME) };
  };
  let n = 0;
  for (let gi = 0; gi < workerData.maxGames; gi++) {
    const g = newGame();
    let p = gi % 2, fromGame = 0, tried = 0, screened = 0;
    for (let turn = 0; turn < 400 && !winner(g); turn++) {
      const dice = [1 + Math.floor(rnd() * 6), 1 + Math.floor(rnd() * 6)];
      if (turn >= 6 && fromGame < 3 && rnd() < 0.2) {
        const v = viewOf(g, p), rem = expandDice(dice), finals = finalPositions(v, rem);
        if (finals.length >= MIN_LEGAL) {
          tried++; n++;
          const a = split(analyzeView(v, rem, { top: 5, rollouts: 60, seed: workerData.seed + n }).cands);
          if (a.next && a.top.win - a.next.win >= GAP_SCREEN && a.top.eq > a.next.eq) {
            screened++;
            const c = split(analyzeView(v, rem, { top: 5, rollouts: 400, seed: 1e6 + workerData.seed + n }).cands);
            const okKeys = c.ok.map((x) => finalOf(v, x.steps));
            if (c.next && okKeys.includes(finalOf(v, a.top.steps)) && c.top.win - c.next.win >= GAP_CONFIRM && c.top.eq > c.next.eq) {
              const finds = (lv, opts) => okKeys.includes(finalOf(v, chooseMove(g, p, dice, lv, () => 0.5, opts)));
              const tier = finds(3, { noise: 0 }) ? 1 : finds(4) ? 2 : finds(5) ? 3 : 4;
              fromGame++;
              parentPort.postMessage({ type: 'puzzle', puzzle: {
                posKey: keyOf(v.mine, v.myOff) + '/' + keyOf(v.opp, v.oppOff) + '/' + dice.join(''),
                mine: Array.from(v.mine), opp: Array.from(v.opp), myOff: v.myOff, oppOff: v.oppOff, dice,
                best: c.top.steps.map(({ r, t, d }) => ({ r, t, d })), key: finalOf(v, c.top.steps), keys: okKeys,
                second: c.next.steps.map(({ r, t, d }) => ({ r, t, d })),
                win: [Math.round(c.top.win * 1000) / 1000, Math.round(c.next.win * 1000) / 1000],
                legal: finals.length, round: Math.floor(turn / 2) + 1, tier, theme: theme(c.top, c.next), rollouts: 400,
              } });
            }
          }
        }
      }
      applySteps(g, p, chooseMove(g, p, dice, 4, rnd));
      p = 1 - p;
    }
    parentPort.postMessage({ type: 'game', tried, screened });
  }
}
