// Writes the app's MainActivity into the generated Android project. Run after
// `npx cap add android` / `npx cap sync android` (sync leaves it alone, add regenerates it):
//   node patch-android.mjs
//
// What it changes: the WebView's text zoom is pinned to 100 %. By default Android applies the
// phone's system font size to every label in the WebView, and the game's HUD is laid out to fit
// around the 3D board: at 115-130 % the panels wrap onto extra rows and cover the board. The
// in-game text sizes are the same as in the browser at that screen width.
import { writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const dir = join(here, 'android', 'app', 'src', 'main', 'java', 'org', 'vichos', 'fevga');
if (!existsSync(dir)) { console.error(`no ${dir} - run "npx cap add android" first`); process.exit(1); }

const src = `package org.vichos.fevga;

import android.os.Bundle;
import com.getcapacitor.BridgeActivity;

// Generated by app/patch-android.mjs - edit that file, not this one.
public class MainActivity extends BridgeActivity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // the HUD is laid out around the board; the system font size would push it over the board
        getBridge().getWebView().getSettings().setTextZoom(100);
    }
}
`;
writeFileSync(join(dir, 'MainActivity.java'), src);
console.log('wrote MainActivity.java (text zoom pinned to 100%)');
