// Writes the app's MainActivity into the generated Android project. Run after
// `npx cap add android` / `npx cap sync android` (sync leaves it alone, add regenerates it):
//   node patch-android.mjs
//
// What it changes: (1) in landscape the status and navigation bars are hidden (immersive; a swipe
// from the edge brings them back for a moment), portrait keeps them. (2) The WebView's text zoom
// is pinned to 100 %. By default Android applies the
// phone's system font size to every label in the WebView, and the game's HUD is laid out to fit
// around the 3D board: at 115-130 % the panels wrap onto extra rows and cover the board. The
// in-game text sizes are the same as in the browser at that screen width.
import { writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const dir = join(here, 'android', 'app', 'src', 'main', 'java', 'org', 'vichos', 'fevga');
if (!existsSync(dir)) { console.error(`no ${dir} - run "npx cap add android" first`); process.exit(1); }

const src = `package org.vichos.fevga;

import android.content.res.Configuration;
import android.os.Bundle;
import androidx.core.view.WindowCompat;
import androidx.core.view.WindowInsetsCompat;
import androidx.core.view.WindowInsetsControllerCompat;
import com.getcapacitor.BridgeActivity;

// Generated by app/patch-android.mjs - edit that file, not this one.
public class MainActivity extends BridgeActivity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // the HUD is laid out around the board; the system font size would push it over the board
        getBridge().getWebView().getSettings().setTextZoom(100);
        applySystemBars(getResources().getConfiguration().orientation);
    }

    // rotation is handled in place (configChanges), so this runs on every turn of the phone
    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        applySystemBars(newConfig.orientation);
    }

    // Landscape: hide the status and navigation bars (a swipe from the edge shows them briefly) -
    // a phone on its side has little enough height for the board. Portrait keeps them.
    private void applySystemBars(int orientation) {
        WindowInsetsControllerCompat bars = WindowCompat.getInsetsController(getWindow(), getWindow().getDecorView());
        bars.setSystemBarsBehavior(WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);
        if (orientation == Configuration.ORIENTATION_LANDSCAPE) bars.hide(WindowInsetsCompat.Type.systemBars());
        else bars.show(WindowInsetsCompat.Type.systemBars());
    }
}
`;
writeFileSync(join(dir, 'MainActivity.java'), src);
console.log('wrote MainActivity.java (immersive landscape, text zoom pinned to 100%)');
